# Generated by Django 2.2.7 on 2019-11-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('student_progress', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=200)),
            ],
        ),
    ]
