# Generated by Django 2.2.7 on 2019-11-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course_syllabus', models.FileField(upload_to='')),
                ('color', models.CharField(default='#007bff', max_length=7)),
            ],
        ),
    ]
