# Generated by Django 2.2.7 on 2019-11-23 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='student_progress',
            new_name='course_duration',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='student_name',
        ),
    ]
