# Generated by Django 2.2.7 on 2019-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20191205_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='color',
            field=models.CharField(default='#1bb4b9', max_length=7),
        ),
    ]
