# Generated by Django 2.2.7 on 2019-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enrolled_courses',
            field=models.ManyToManyField(related_name='enrolled_courses', to='course.Course'),
        ),
    ]
