# Generated by Django 2.2.7 on 2019-11-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('user', '0003_auto_20191124_0147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='course.Course'),
        ),
    ]
